name: David Cushing artist
favicon: null
layout_spectrum: 0.8113065771758556
typography_spectrum: 0.8106416875962168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edc19c'
    - '#b78f76'
    - '#8b6250'
    - '#522414'
    - '#250700'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
